apiVersion: v1
kind: Service
metadata:
  name: service-python
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    run: pod-python
  type: NodePort
